"use client";
import Link from "next/link";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { AuthGuard } from "@/components/auth-guard";
import { Modal } from "@/components/modal";
import { api, json } from "@/lib/api";
import type { Board } from "@/types/api";

export default function BoardsPage() {
  const [boards, setBoards] = useState<Board[]>([]); const [busy, setBusy] = useState(true); const [error, setError] = useState(""); const [showCreate, setShowCreate] = useState(false); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setBusy(true); try { setBoards(await api<Board[]>("/boards")); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar os quadros."); } finally { setBusy(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function create(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setSaving(true); const name = new FormData(e.currentTarget).get("name"); try { await api<Board>("/boards", json("POST", { name })); setShowCreate(false); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Falha ao criar quadro."); } finally { setSaving(false); } }
  async function remove(board: Board) { if (!window.confirm(`Excluir o quadro “${board.name}”? Esta ação não pode ser desfeita.`)) return; try { await api(`/boards/${board.id}`, json("DELETE")); setBoards((items) => items.filter((item) => item.id !== board.id)); } catch (e) { setError(e instanceof Error ? e.message : "Falha ao excluir."); } }
  return <AuthGuard><main className="mx-auto w-full max-w-7xl flex-1 px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-indigo-600">ESPAÇO DE TRABALHO</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Meus quadros</h1><p className="mt-2 text-slate-500">Acompanhe o trabalho da sua equipe em um só lugar.</p></div><button onClick={() => setShowCreate(true)} className="primary-button">＋ Novo quadro</button></div>{error && <p role="alert" className="mt-6 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{busy ? <p className="py-16 text-center text-slate-500">Carregando quadros…</p> : boards.length === 0 ? <div className="mt-10 rounded-2xl border border-dashed border-slate-300 bg-white py-16 text-center"><div className="text-4xl">▤</div><h2 className="mt-4 font-semibold">Seu espaço começa aqui</h2><p className="mt-1 text-sm text-slate-500">Crie um quadro para organizar as tarefas do time.</p><button onClick={() => setShowCreate(true)} className="secondary-button mt-5">Criar primeiro quadro</button></div> : <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{boards.map((board) => <article key={board.id} className="group relative rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><Link href={`/boards/${board.id}`} className="block"><span className="grid size-11 place-items-center rounded-xl bg-indigo-50 text-xl text-indigo-700">▤</span><h2 className="mt-4 pr-8 font-semibold text-slate-900">{board.name}</h2><p className="mt-1 text-sm text-slate-500">{board.columns?.length ?? 0} colunas</p></Link><button aria-label={`Excluir ${board.name}`} title="Excluir quadro" onClick={() => void remove(board)} className="absolute right-4 top-4 rounded-lg px-2 py-1 text-slate-400 hover:bg-red-50 hover:text-red-600">•••</button></article>)}</div>}{showCreate && <Modal title="Criar quadro" close={() => setShowCreate(false)}><form onSubmit={create} className="space-y-4"><label className="field-label">Nome do quadro<input autoFocus required name="name" maxLength={80} placeholder="Ex.: Lançamento do produto" className="field-input" /></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setShowCreate(false)} className="secondary-button">Cancelar</button><button disabled={saving} className="primary-button">{saving ? "Criando…" : "Criar quadro"}</button></div></form></Modal>}</main></AuthGuard>;
}
